### ISSUE TITLE
build error when 1st try the project

### ISSUE THREAD

**Issue by gaowayne** [tokio-rs/io-uring#164]
could you please check why I suffer this build error?

``` 
[root@localhost io-uring]# cargo run --package io-uring-test
    Updating crates.io index
  Downloaded remove_dir_all v0.5.3
  Downloaded tempfile v3.3.0
  Downloaded cfg-if v1.0.0
  Downloaded bitflags v1.3.2
  Downloaded fastrand v1.8.0
  Downloaded anyhow v1.0.68
  Downloaded once_cell v1.16.0
  Downloaded libc v0.2.139
  Downloaded socket2 v0.4.7
  Downloaded 9 crates (838.7 KB) in 1.12s
   Compiling libc v0.2.139
   Compiling anyhow v1.0.68
   Compiling io-uring v0.5.10 (/mnt/sda/sda5/wayne/rust/io_uring/io-uring)
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.3.2
   Compiling remove_dir_all v0.5.3
   Compiling fastrand v1.8.0
   Compiling once_cell v1.16.0
   Compiling socket2 v0.4.7
   Compiling tempfile v3.3.0
   Compiling io-uring-test v0.1.0 (/mnt/sda/sda5/wayne/rust/io_uring/io-uring/io-uring-test)
error[E0658]: destructuring assignments are unstable
   --> io-uring-test/src/tests/register_buf_ring.rs:491:5
    |
491 |     _ = ring;
    |     ^
    |
    = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information

error[E0658]: destructuring assignments are unstable
   --> io-uring-test/src/tests/register_buf_ring.rs:491:7
    |
491 |     _ = ring;
    |     - ^
    |     |
    |     cannot assign to this expression
    |
    = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `io-uring-test` due to 2 previous errors
[root@localhost io-uring]# 
```

**Comment by gaowayne** [comment]
[root@localhost io-uring]# uname -a
Linux localhost.localdomain 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost io-uring]#

**Comment by FrankReh** [comment]
What version of rust compiler are you using? Can you run `rustc --version` and `cargo --version`?

I think most of us are using the latest. I've seen some work to get it to still compile with 1.48 on Debian but I don't know if the test package was tried with that compiler.

That line looks unnecessary and should probably be removed but easier would be to see if your compile problem is caused by an old compiler version.

**Comment by FrankReh** [comment]
I've created a PR, #165, to remove that line and bump the version. If you are in a rush, you may want to use that fork or remove the line from a local copy of the repo for your own build.

**Comment by gaowayne** [comment]
> rustc --version
```
[root@localhost uring_examples]# rustc --version
rustc 1.56.1 (Fedora 1.56.1-1.fc33)
[root@localhost uring_examples]# 
[root@localhost uring_examples]# cargo --version
cargo 1.56.0
[root@localhost uring_examples]# 
```
