### ISSUE TITLE
Support RISC-V?

### ISSUE THREAD

**Issue by SUPERCILEX** [tokio-rs/io-uring#307]
A compilation error was introduced in https://github.com/tokio-rs/io-uring/pull/301 for riscv. Can it be supported natively?

For searchability:
```
error: The prebuilt `sys.rs` may not be compatible with your target,
       please use bindgen feature to generate new `sys.rs` of your arch
       or use `--cfg=io_uring_skip_arch_check` to skip the check.
```

**Comment by quininer** [comment]
Sure, but I don't have a riscv device to test with, and if it's guaranteed on CI, I'd be happy to take it.

**Comment by quininer** [comment]
Anyway, now you can skip check using `io_uring_skip_arch_check`, or specify your own binding using `io_uring_use_own_sys`
